# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vMtVAw9ogNJ5_7RsGN0p59PlBU4lOCBe
"""

import pandas as pd
data_corp = pd.read_csv("https://raw.githubusercontent.com/Kseniya-Loko/Comput_linguistics/main/ruscorpora_content.csv", sep = ";")
data_corp
import re
def find_adj(regular):
  result = re.search(r'(\b\w+(ая|ую|ой)\b(\ (тоск(а|е|и|ой|у))))|((тоск(а|е|и|ой|у))\ )(\b\w+(ая|ую|ой)\b)', regular)
  if result!= None:
    return(result.group())
  else:
    return('None')
#data_corp["Noun and Adj"] = data_corp["Full context"].apply(lambda regular: re.sub(r'(\b\w+(ая|ую|ой)\b(\ (тоск(а|е|и|ой|у))))|((тоск(а|е|и|ой|у))\ )(\b\w+(ая|ую|ой)\b)', ' ', regular))
none_adj_none = data_corp["Full context"].map(find_adj, na_action=None)
data_corp["None and Adj"] = none_adj_none
data_corp["None and Adj"]
data_corp.to_excel('search_result.xlsx', sheet_name='1')

