# -*- coding: utf-8 -*-
"""Visual_parallel_corp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pdifaL_x8SJ8hazSvpukhtXQUGiPn2n
"""

import pandas as pd
data_engwords = pd.read_csv("https://raw.githubusercontent.com/Kseniya-Loko/Comput_linguistics/main/Parallel_corp_eng.csv", sep = ";")
data_engwords

data_engwords["Frequency Corp"] = data_engwords["Count Wordform"] / data_engwords["CountDocuments"]
data_engwords

data_engwords.plot(x = "Noun eng", y = "Frequency Corp", figsize = (10, 10), kind = "bar")

data_engwords.plot(x = "Noun eng", y = "CountChoice", figsize = (10, 10), kind = "bar")

data_engwords["Persent choice_corp"] = data_engwords["CountChoice"] * 100 / data_engwords["Count Wordform"]
data_engwords.plot( x = "Noun eng", y = "Persent choice_corp", figsize = (10, 10), kind = "bar")
data_engwords

